services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .env:/var/www/.env
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service

  db_app:
    image: mariadb
    restart: unless-stopped
    environment:
      DB_DATABASE: smart_home
      MYSQL_ROOT_PASSWORD: 1qazxsw2A
    volumes:
      - ./app/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
    container_name: db
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local